[format]
line-width = 80
indent-width = 4
skip = ["lapply", "sapply", "vapply", "mapply", "Map", "Position", "validate_numeric", "validate_nirs_channels", "validate_time_channel", "validate_event_channel", "validate_sample_rate", "compute_local_windows", "compute_local_fun", "compute_outliers"]